services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - COMPOSER_HOME=/var/www/html/.composer
    environment:
      COMPOSER_HOME: /var/www/html/.composer
    volumes:
      - ./:/var/www/html